### ISSUE TITLE
Random "ActionView::Template::Error: end of file reached" errors

### ISSUE THREAD

**Issue by morgoth** [jfirebaugh/konacha#123]
Recently I'm getting random errors like in the topic. I'm providing backtrace at the bottom.
Also sometimes Konacha "freezes" without any response. Not sure if this has something to do with error described above, because this happens separately.
If you like, you can take a look at repo: https://github.com/qoobaa/bridge-ember
Reported here with `36f0b617ec68fe9044a924d360e6470d86645a59` commit on master.

```
wojtek@ibm:~/Projects/bridge-ember$ bin/rails c
Loading development environment (Rails 4.0.0.beta1)
2.0.0p0 :001 > Konacha.run
Processing by Konacha::SpecsController#parent as HTML
  Rendered /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/parent.html.erb (30.3ms)
Completed 200 OK in 42ms (Views: 39.1ms)
Processing by Konacha::SpecsController#iframe as HTML
Processing by Konacha::SpecsController#iframe as HTML
  Parameters: {"name"=>"models/card_test"}
Processing by Konacha::SpecsController#iframe as HTML
  Parameters: {"name"=>"controllers/board_controller_test"}
  Parameters: {"name"=>"models/bid_test"}
Processing by Konacha::SpecsController#iframe as HTML
  Parameters: {"name"=>"lib/utils_test"}
  Rendered /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/iframe.html.erb (1168.2ms)
Completed 500 Internal Server Error in 1195ms
ActionView::Template::Error: end of file reached
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/marshal.rb:4:in `load'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/marshal.rb:4:in `load_with_autoloading'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/cache/file_store.rb:19:in `block in []'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/cache/file_store.rb:19:in `open'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/cache/file_store.rb:19:in `open'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/cache/file_store.rb:19:in `[]'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:14:in `cache_get'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:84:in `cache_get_hash'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:54:in `cache_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:93:in `build_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/base.rb:287:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:61:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:44:in `block in init_with'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:37:in `map'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:37:in `init_with'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/asset.rb:24:in `from_hash'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:54:in `cache_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:93:in `build_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/base.rb:287:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:61:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:44:in `block in init_with'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:37:in `map'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/processed_asset.rb:37:in `init_with'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/asset.rb:24:in `from_hash'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:54:in `cache_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:93:in `build_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/base.rb:287:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:61:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/bundled_asset.rb:39:in `init_with'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/asset.rb:24:in `from_hash'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/caching.rb:54:in `cache_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:93:in `build_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/base.rb:287:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/index.rb:61:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/environment.rb:75:in `find_asset'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-2.9.0/lib/sprockets/base.rb:295:in `[]'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-rails-2.0.0.rc3/lib/sprockets/rails/helper.rb:141:in `lookup_asset_for_path'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-rails-2.0.0.rc3/lib/sprockets/rails/helper.rb:90:in `block in javascript_include_tag'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-rails-2.0.0.rc3/lib/sprockets/rails/helper.rb:89:in `map'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/sprockets-rails-2.0.0.rc3/lib/sprockets/rails/helper.rb:89:in `javascript_include_tag'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/iframe.html.erb:13:in `__home_wojtek__rvm_gems_ruby_______p__gems_konacha_______app_views_konacha_specs_iframe_html_erb___1354590329585455485_47375160'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/template.rb:143:in `block in render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications.rb:160:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/template.rb:141:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/abstract_renderer.rb:23:in `block in instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications.rb:158:in `block in instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications.rb:158:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/abstract_renderer.rb:23:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/template_renderer.rb:17:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/renderer.rb:36:in `render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_view/renderer/renderer.rb:17:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/rendering.rb:119:in `_render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/rendering.rb:112:in `render_to_body'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/rendering.rb:97:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/rendering.rb:16:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
    /home/wojtek/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/benchmark.rb:5:in `ms'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.beta1/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:40:in `render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/base.rb:189:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/callbacks.rb:373:in `_run__1412963378448116401__process_action__callbacks'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/callbacks.rb:78:in `run_callbacks'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/callbacks.rb:17:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications.rb:158:in `block in instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.beta1/lib/active_support/notifications.rb:158:in `instrument'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.beta1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/base.rb:136:in `process'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/abstract_controller/rendering.rb:44:in `process'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal.rb:196:in `dispatch'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_controller/metal.rb:232:in `block in action'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/routing/route_set.rb:78:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/routing/route_set.rb:78:in `dispatch'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/routing/route_set.rb:46:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/journey/router.rb:69:in `block in call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/journey/router.rb:57:in `each'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/journey/router.rb:57:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/actionpack-4.0.0.beta1/lib/action_dispatch/routing/route_set.rb:651:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.beta1/lib/rails/engine.rb:510:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.beta1/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.0.2/lib/capybara/server.rb:19:in `call'
    /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /home/wojtek/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /home/wojtek/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /home/wojtek/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
  Rendered /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/iframe.html.erb (3392.5ms)
Completed 200 OK in 3398ms (Views: 3396.7ms)
  Rendered /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/iframe.html.erb (3406.1ms)
Completed 200 OK in 3412ms (Views: 3410.0ms)
  Rendered /home/wojtek/.rvm/gems/ruby-2.0.0-p0/gems/konacha-2.5.1/app/views/konacha/specs/iframe.html.erb (3396.6ms)
Completed 200 OK in 3417ms (Views: 3415.8ms)
F..............................

  Failed:  models/card_test.js.coffee
    Error: Failed to load models/card_test.js.coffee.
Perhaps it failed to compile? Check the rake output for errors.

Finished in 0.23 seconds
31 examples, 1 failed, 0 pending
 => false 

```

**Comment by hugocorbucci** [comment]
Seems like 
```
config.assets.configure do |env|
  env.cache = ThreadSafe::Cache.new
end
```
worked for me. Just added it to my test.rb instead since it works just fine when precompiling on the server.

**Comment by hugocorbucci** [comment]
As an update, this went downhill since konacha 3.5.0 as it upgraded sprockets and it seems ThreadSafe::Cache no longer works with sprockets 3.x (doesn't comply with at least the `set` method).

I was getting the following error:
```
ActionView::Template::Error:
       undefined method `set' for #<ThreadSafe::Cache:0x007ff732b59100>
```

Had to remove:
```
config.assets.configure do |env|
  env.cache = ThreadSafe::Cache.new
end
```
