### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'window.top.Konacha.getEvents')

### ISSUE THREAD

**Issue by bradrobertson** [jfirebaugh/konacha#160]
Just attempting to upgrade to rails 4. we were originally getting reference errors to `chai` and `mocha`, but I added `config.assets.prefix = "/dev-assets"` to our development.rb and now we fail with the above statement. I've pasted the stack trace below. We're using;

konacha 3.0.0
poltergeist 1.5
phantomjs 1.9.1

Any thoughts?

```
rake aborted!
One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

TypeError: 'undefined' is not an object (evaluating 'window.top.Konacha.getEvents')
TypeError: 'undefined' is not an object (evaluating 'window.top.Konacha.getEvents')
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1
    at phantomjs://webpage.evaluate():1/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/poltergeist-1.5.0/lib/capybara/poltergeist/browser.rb:275:in `command'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/poltergeist-1.5.0/lib/capybara/poltergeist/browser.rb:106:in `evaluate'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/poltergeist-1.5.0/lib/capybara/poltergeist/driver.rb:130:in `evaluate_script'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/capybara-2.2.0/lib/capybara/session.rb:342:in `evaluate_script'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/konacha-3.0.0/lib/konacha/runner.rb:24:in `run'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/konacha-3.0.0/lib/konacha/runner.rb:7:in `start'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/konacha-3.0.0/lib/konacha.rb:21:in `run'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/konacha-3.0.0/lib/tasks/konacha.rake:9:in `block (2 levels) in <top (required)>'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/bin/ruby_executable_hooks:15:in `eval'
/Users/brad/.rvm/gems/ruby-2.0.0-p353@influitive/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => konacha:run
(See full trace by running task with --trace)
```

**Comment by CyborgMaster** [comment]
I'm having this same error.  It seems like `konacha:run` only works if a rails server is up and running to serve the assets.  Is this correct?  Can konacha run standalone?
