### ISSUE TITLE
Tests failing due to Load Error

### ISSUE THREAD

**Issue by alexauritt** [jfirebaugh/konacha#204]
```
/gems/2.2.0/gems/rspec-core-3.2.3/lib /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/aauritt/code/open_source/konacha/lib/konacha.rb:1:in `require': cannot load such file -- tilt (LoadError)
	from /Users/aauritt/code/open_source/konacha/lib/konacha.rb:1:in `<top (required)>'
	from /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
	from /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `each'
	from /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/aauritt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
```

**Comment by alexauritt** [comment]
![screen shot 2015-05-01 at 12 24 19 pm](https://cloud.githubusercontent.com/assets/222745/7433192/e377ca0c-effc-11e4-8772-60a8c2af1252.png)
