### ISSUE TITLE
Rack application timed out during boot

### ISSUE THREAD

**Issue by CyborgMaster** [jfirebaugh/konacha#231]
I'm getting a weird hang after updating to Thin 1.70.  When running `rake konacha:run` I get the following error `Error communicating with browser process: Rack application timed out during boot`

Konacha 4.0.0
Capybara 2.7.1
Thin 1.7.0

```
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
rake aborted!
Error communicating with browser process: Rack application timed out during boot
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/server.rb:109:in `rescue in boot'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/server.rb:99:in `boot'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/session.rb:72:in `initialize'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:41:in `new'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:41:in `session'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:18:in `run'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:7:in `start'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha.rb:21:in `run'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/tasks/konacha.rake:9:in `block (2 levels) in <top (required)>'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/bin/ruby_executable_hooks:15:in `eval'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/bin/ruby_executable_hooks:15:in `<main>'
Timeout::Error: execution expired
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/server.rb:106:in `join'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/server.rb:106:in `block in boot'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/server.rb:106:in `boot'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/capybara-2.7.1/lib/capybara/session.rb:72:in `initialize'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:41:in `new'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:41:in `session'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:18:in `run'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha/runner.rb:7:in `start'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/konacha.rb:21:in `run'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/konacha-4.0.0/lib/tasks/konacha.rake:9:in `block (2 levels) in <top (required)>'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/bin/ruby_executable_hooks:15:in `eval'
/Users/jeremy/.rvm/gems/ruby-2.3.1@allynova/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => konacha:run
```

**Comment by CyborgMaster** [comment]
Turns out this was my own fault.  I was using Thin as a workaround to reduce hangs (suggested here https://github.com/jfirebaugh/konacha/issues/146#issuecomment-28609596).  I needed to update the server registration to include the host like so:

``` ruby
    Capybara.register_server :thin do |app, port, host|
      require 'rack/handler/thin'
      Rack::Handler::Thin.run(app, Port: port, Host: host)
    end
```
